### ISSUE TITLE
What are your preferred tools and libraries?

### ISSUE THREAD

**Issue by justxi** [justxi/rocm#54]
Due to the fact that ROCm is based on a lot of tools and libraries, I added all supported by ROCM 2.6 to README.md. This does not necessarily mean that all can be added in the near future, due to the fact that we have to solve the main problems first:
- unbundle rocm-opencl-runtime
- build HIP based on "clang" (HIP-clang)
- clean up repository

To focus on the desired tools and libraries every user could add a short statement, which libraries are important for his work.

So besides the basic tools my interest is to get to work
- rocBLAS
- rocALUTION 

and as a prerequisite 
- rocPRIM
- rocSPARSE

**Comment by davidrohr** [comment]
I think thrust and cub are a must, if one wants to port CUDA code.

**Comment by davidrohr** [comment]
For hip-clang, I have found ROCm-Developer-Tools/HIP#1196 and followed the recipe. It seems even with hip-clang based on our llvm-roc, we'll still need hcc since hip still depends on it (hopefully, it will change with one of the following releases). I build hip following the recipe, and could build and install. What comes out can actually compile .hip.cpp files, but it will fail during linking with:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/a-a5df7e.o: in function `__hip_module_ctor':
a.hip.cpp:(.text+0x706): undefined reference to `__hipRegisterFatBinary'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: a.hip.cpp:(.text+0x739): undefined reference to `__hipRegisterFunction'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/a-a5df7e.o: in function `__hip_module_dtor':
a.hip.cpp:(.text+0x75e): undefined reference to `__hipUnregisterFatBinary'
```

**Comment by justxi** [comment]
But building "hip" the old way (without hip-clang) it works?

**Comment by davidrohr** [comment]
Yes, hip with hcc works, hip with hip-clang works with master but not with 2.7.
I already added this to our ebuild in #56

**Comment by justxi** [comment]
Ok, I think the current user base has all they need. I close this issue due to inactivity.
Please reopen if there is a need for further ebuilds.

**Comment by heroxbd** [comment]
Now strangely, hip-clang is lagging behind at 2.10.0 but hip itself has been upgraded to 3.1.0.  cf. https://github.com/RadeonOpenCompute/hcc/issues/1421

**Comment by justxi** [comment]
Yes, I am also a little bit confused about the future of the compiler.
I have currently limited time to work on this. Hopefully, I am  back in few weeks.
If you have further informations, please let me know.

**Comment by heroxbd** [comment]
> Yes, I am also a little bit confused about the future of the compiler.
> I have currently limited time to work on this. Hopefully, I am back in few weeks.
> If you have further informations, please let me know.

I have figure it out and good news comes.  There is no AMD-customized hip-clang 3.x because it has been upstreamed to be into official LLVM.  https://github.com/ROCm-Developer-Tools/HIP/commit/af697eaefed7806d1d561f9f5087f07f7013a4ec

**Comment by justxi** [comment]
Thats good news, but it seems to need HCC, isn´t it?

**Comment by heroxbd** [comment]
Wilfried Holzke <notifications@github.com> writes:

> Thats good news, but it seems to need HCC, isn´t it?

I am not sure know yet.
