### ISSUE TITLE
bump to rocm-3.7.0

### ISSUE THREAD

**Issue by littlewu2508** [justxi/rocm#160]
ROCm just released version 3.7.0. Some ebuilds already have 3.7.0 version, and there occurs some new problems.

**Comment by littlewu2508** [comment]
I met a problem with hip and llvm-roc-3.7.0:

I used hipcc to compile a simple hip program. When linking, the linker cannot find `libclang_rt.builtins-x86_64.a`.

Comparing version 3.5.1 and 3.7.0, there's a difference of the linking command: hip-3.7.0 add -lclang_rt.builtins-x86_64 flag

The linking part of output of hipcc -v (3.5.1) :
```
/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld" --hash-style=both --eh-frame-hdr -m elf_x86_64 -dynamic-linker /opt/gentoo/lib64/ld-linux-x86-64.so.2 -o hip /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crt1.o /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crti.o /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/crtbegin.o -L/opt/gentoo/usr/lib/hip/3.5/lib -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0 -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64 -L/opt/gentoo/lib/../lib64 -L/opt/gentoo/usr/lib/../lib64 -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/lib -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../.. -L/opt/gentoo/usr/lib64/llvm/roc/bin/../lib -L/opt/gentoo/lib -L/opt/gentoo/usr/lib -lgcc_s -lgcc -lpthread -lm /tmp/main-9136b7.o /tmp/test_hip_fun-40c7c8.o --enable-new-dtags --rpath=/opt/gentoo/usr/lib/hip/3.5/lib:/opt/gentoo/usr/lib -lhip_hcc -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/crtend.o /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crtn.o
```

while version 3.7.0:
```
"/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld" --hash-style=both --eh-frame-hdr -m elf_x86_64 -dynamic-linker /opt/gentoo/lib64/ld-linux-x86-64.so.2 -o hip /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crt1.o /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crti.o /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/crtbegin.o -L/opt/gentoo/usr/lib/hip/3.7/lib -L/opt/gentoo/usr/lib/llvm/roc/bin/../lib/clang/11.0.0/lib/linux -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0 -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64 -L/opt/gentoo/lib/../lib64 -L/opt/gentoo/usr/lib/../lib64 -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/lib -L/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../.. -L/opt/gentoo/usr/lib64/llvm/roc/bin/../lib -L/opt/gentoo/lib -L/opt/gentoo/usr/lib -lgcc_s -lgcc -lpthread -lm /tmp/main-643b6f.o /tmp/test_hip_fun-0ded58.o --enable-new-dtags --rpath=/opt/gentoo/usr/lib/hip/3.7/lib:/opt/gentoo/usr/lib -lamdhip64 -lnuma -lclang_rt.builtins-x86_64 -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/crtend.o /opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crtn.o
/opt/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclang_rt.builtins-x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by littlewu2508** [comment]
sys-devel/clang contains libclang_rt.builtins-x86_64.a, and I can link it into ${EPREFIX}/usr/lib64/llvm/roc/lib to solve. But apparently this is not a workaround

**Comment by littlewu2508** [comment]
> 
> 
> sys-devel/clang contains libclang_rt.builtins-x86_64.a, and I can link it into ${EPREFIX}/usr/lib64/llvm/roc/lib to solve. But apparently this is not a workaround

The currect workaround: 

adding `compiler-rt` to ` -DLLVM_ENABLE_PROJECTS` in llvm-roc-3.7.0.ebuild

Have anyone else meet the same problem as I described?

**Comment by justxi** [comment]
@littlewu2508 
Yes, I have the problem. A workaround was to copy the file from compiler-rt (11.0.0_rc2) to "/usr/lib64". But thats not a solution.
I will try your idea to add compiler-rt to the llvm-roc ebuild.

After this is fixed I get a violation while accessing "/dev/kfd". Do have the same problem?

**Comment by littlewu2508** [comment]
> 
> 
> @littlewu2508
> Yes, I have the problem. A workaround was to copy the file from compiler-rt (11.0.0_rc2) to "/usr/lib64". But thats not a solution.
> I will try your idea to add compiler-rt to the llvm-roc ebuild.
> 
> After this is fixed I get a violation while accessing "/dev/kfd". Do have the same problem?
> 
> Furthermore, when this problem is fixed, I start to update the sci-libs ebuilds.

No, I haven't observed any problem with /dev/kfd since upgrading to rocm-3.7.0. Can you describe this violation more explicitly?

**Comment by justxi** [comment]
I get:
```
>>> Emerging (1 of 1) dev-libs/rccl-3.7.0::rocm
 * rccl-3.7.0.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                            [ ok ]
>>> Unpacking source...
>>> Unpacking rccl-3.7.0.tar.gz to /var/tmp/portage/dev-libs/rccl-3.7.0/work
>>> Source unpacked in /var/tmp/portage/dev-libs/rccl-3.7.0/work
>>> Preparing source in /var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-rocm-3.7.0 ...
 * Applying rccl-2.7.0-change_install_location.patch ...
patching file CMakeLists.txt
Hunk #1 succeeded at 200 (offset 38 lines).
Hunk #2 succeeded at 229 with fuzz 1 (offset 38 lines).                                                                                                                                                     [ ok ]
 * Hardcoded definition(s) removed in CMakeLists.txt:
 *  set(CMAKE_INSTALL_PREFIX "/opt/rocm" CACHE PATH "")
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-rocm-3.7.0 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-3.7.0_build"
cmake -C /var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-3.7.0_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CXX_FLAGS=--amdgpu-target=gfx803 -Wno-dev -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-3.7.0_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-rocm-3.7.0
loading initial cache file /var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-3.7.0_build/gentoo_common_config.cmake
-- The CXX compiler identification is Clang 11.0.0
-- Check for working CXX compiler: /usr/lib/hip/3.7/bin/hipcc
-- Check for working CXX compiler: /usr/lib/hip/3.7/bin/hipcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
 * ACCESS DENIED:  open_wr:      /dev/kfd
 * ACCESS DENIED:  open_wr:      /dev/kfd
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- HIP compiler: clang
-- HIP runtime: ROCclr
 * ACCESS DENIED:  open_wr:      /dev/kfd
 * ACCESS DENIED:  open_wr:      /dev/kfd
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               
C++             --amdgpu-target=gfx803
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed
Module          -Wl,-O1 -Wl,--as-needed
Shared          -Wl,-O1 -Wl,--as-needed

-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/portage/dev-libs/rccl-3.7.0/work/rccl-3.7.0_build
>>> Source configured.
 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/tmp/portage/dev-libs/rccl-3.7.0/temp/sandbox.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /dev/kfd
A: /dev/kfd
R: /dev/kfd
C: /usr/bin/rocminfo 

F: open_wr
S: deny
P: /dev/kfd
A: /dev/kfd
R: /dev/kfd
C: /usr/bin/rocminfo 

F: open_wr
S: deny
P: /dev/kfd
A: /dev/kfd
R: /dev/kfd
C: /usr/bin/rocminfo 

F: open_wr
S: deny
P: /dev/kfd
A: /dev/kfd
R: /dev/kfd
C: /usr/bin/rocminfo 
 * --------------------------------------------------------------------------------

>>> Failed to emerge dev-libs/rccl-3.7.0, Log file:


```

**Comment by justxi** [comment]
@littlewu2508 Adding "compiler-rt" to "-DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt"" solved the first problem.

@candrews HIP needs "compiler-rt". Should I enable it in general or only with a USE flag?

**Comment by justxi** [comment]
@littlewu2508 I fixed the sandbox violation ... see: https://github.com/justxi/rocm/blob/master/dev-libs/rccl/rccl-3.7.0.ebuild

**Comment by justxi** [comment]
The problems discussed here seem to be fixed.

**Comment by justxi** [comment]
@littlewu2508 I have updated all ebuilds. 
"rocBLAS" has built in "Tensile" support, which is needed by "miopen".

**Comment by pshirshov** [comment]
@justxi Maybe I'm doing something wrong but I still cannot build rocBLAS/rocPRIM/etc because of that issue:

```
cat /var/tmp/portage/sci-libs/rocPRIM-3.7.0/temp/build.log
 * Package:    sci-libs/rocPRIM-3.7.0
 * Repository: rocm
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 * Hardcoded definition(s) removed in CMakeLists.txt:
 *  set(CMAKE_INSTALL_PREFIX "/opt/rocm" CACHE PATH "Install path prefix, prepend
 *    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Choose the type of build." FOR
>>> Working in BUILD_DIR: "/var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build"
cmake -C /var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_PREFIX=/usr/ -DAMDGPU_TARGETS=gfx803;gfx900;gfx906;gfx908 -DBUILD_TEST=OFF -DBUILD_BENCHMARK=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-rocm-3.7.0
loading initial cache file /var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build/gentoo_common_config.cmake
-- The CXX compiler identification is Clang 11.0.0
-- Check for working CXX compiler: /usr/lib/hip/3.7/bin/hipcc
-- Check for working CXX compiler: /usr/lib/hip/3.7/bin/hipcc -- broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/usr/lib/hip/3.7/bin/hipcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_d4559 && [1/2] Building CXX object CMakeFiles/cmTC_d4559.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_d4559
    FAILED: cmTC_d4559
    : && /usr/lib/hip/3.7/bin/hipcc  -march=native -O3 -pipe  -Wl,-O1 -Wl,--as-needed CMakeFiles/cmTC_d4559.dir/testCXXCompiler.cxx.o  -o cmTC_d4559   && :
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclang_rt.builtins-x86_64
    clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:29 (project)


-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build/CMakeFiles/CMakeOutput.log".
See also "/var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build/CMakeFiles/CMakeError.log".
 * ERROR: sci-libs/rocPRIM-3.7.0::rocm failed (configure phase):
 *   cmake failed
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_configure
 *   environment, line 2073:  Called cmake-utils_src_configure
 *   environment, line  855:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 *
 * If you need support, post the output of `emerge --info '=sci-libs/rocPRIM-3.7.0::rocm'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/rocPRIM-3.7.0::rocm'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/rocPRIM-3.7.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/rocPRIM-3.7.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-3.7.0_build'
 * S: '/var/tmp/portage/sci-libs/rocPRIM-3.7.0/work/rocPRIM-rocm-3.7.0'
```

Could you help me please?

**Comment by justxi** [comment]
Could you try to reload your environment settings or simply reboot your system?

**Comment by pshirshov** [comment]
Nope, that doesn't help. Though from what I can see, the `compiler-rt` is not in the gentoo main tree yet.

So I created my local copy of your ebuild, applied that patch - and now everything is okay... Could you propagate the change into the main tree please?

**Comment by justxi** [comment]
Oh sorry, I forget to add the change.
Thanks for the hint.

**Comment by pshirshov** [comment]
Meh. Unfortunately I still can't build hipBLAS:

[build.log](https://github.com/justxi/rocm/files/5219588/build.log)

Do you have any idea how to fix that?

**Comment by pshirshov** [comment]
Update: I believe this happens because I have `nvcc` installed in my system...

**Comment by justxi** [comment]
Ok, because I thougt it worked on my system.

**Comment by pshirshov** [comment]
I just don't know how to do it. Probably I need another customized ebuild and I need to figure out how to disable `nvcc` support in hipblas.

**Comment by pshirshov** [comment]
Probably you need to add `-DTRY_CUDA=OFF` to  cmake options in your ebuild. Could you please?

**Comment by pshirshov** [comment]
Yeah, it works if I modify the ebuild this way:

```
        local mycmakeargs=(
                -DTRY_CUDA=OFF
                -DCMAKE_INSTALL_PREFIX=/usr
                -DCMAKE_PREFIX_PATH="${HIP_PATH}"
        )
```

Please fix :)

**Comment by pshirshov** [comment]
https://github.com/justxi/rocm/pull/165

**Comment by justxi** [comment]
-> https://github.com/justxi/rocm/blob/master/sci-libs/hipBLAS/hipBLAS-3.7.0-r1.ebuild

**Comment by pshirshov** [comment]
Thanks!

**Comment by justxi** [comment]
Thank you for your hint.

And please try -> https://github.com/justxi/rocm/blob/master/sys-devel/llvm-roc/llvm-roc-3.7.0-r1.ebuild

**Comment by pshirshov** [comment]
For some reason llvm-roc r1 ebuild failed:

```
FAILED: lib/libLLVMObject.so.11roc                                                                                                                                                                                                                                             : && /usr/bin/x86_64-pc-linux-gnu-g++ -fPIC -march=native -O3 -pipe -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-ma
ybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections  -Wl,-O1 -Wl,--as-needed -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/var/tmp/portage/sys-devel/llvm-roc-3.7.0-r1/work/llvm-roc-3.7.0_build/./lib  -Wl,-O3 -Wl,--gc-sections -shared -Wl,-soname,libLLVMObject.so.11roc -o lib/libLLVMObject.so.11roc lib/Object/CMakeFiles/LLVMObject.dir/Archive.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ArchiveWriter.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Binary.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/COFFImportFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/COFFModuleDefinition.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/COFFObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Decompressor.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ELF.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ELFObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Error.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/IRObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/IRSymtab.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/MachOObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/MachOUniversal.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Minidump.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/ModuleSymbolTable.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Object.cpp.o
 lib/Object/CMakeFiles/LLVMObject.dir/ObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/RecordStreamer.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/RelocationResolver.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/SymbolicFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/Sym
bolSize.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/TapiFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/TapiUniversal.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/WasmObjectFile.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/WindowsMachineFlag.cpp.o lib/Object/CMakeFiles/LLVMOb
ject.dir/WindowsResource.cpp.o lib/Object/CMakeFiles/LLVMObject.dir/XCOFFObjectFile.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMBitReader.so.11roc  lib/libLLVMCore.so.11roc  lib/libLLVMMCParser.so.11roc  lib/libLLVMTextAPI.so.11roc  lib/libLLVMMC.so.11roc  lib/libLLV
MBinaryFormat.so.11roc  lib/libLLVMSupport.so.11roc  -Wl,-rpath-link,/var/tmp/portage/sys-devel/llvm-roc-3.7.0-r1/work/llvm-roc-3.7.0_build/lib && :
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/Object/CMakeFiles/LLVMObject.dir/ArchiveWriter.cpp.o: in function `llvm::writeArchive(llvm::StringRef, llvm::ArrayRef<llvm::NewArchiveMember>, bool, llvm::object::Archive::Kind, bool, bool
, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >)':
ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x1c58): undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x1c8b):
 undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x1cb8):
 undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x1ce3):
 undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x1d10):
 undefined reference to `llvm::raw_string_ostream::current_pos() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/Object/CMakeFiles/LLVMObject.dir/ArchiveWriter.cpp.o:ArchiveWriter.cpp:(.text._ZN4llvm12writeArchiveENS_9StringRefENS_8ArrayRefINS_16NewArchiveMemberEEEbNS_6object7Archive4KindEbbSt10uniqu
e_ptrINS_12MemoryBufferESt14default_deleteIS8_EE+0x1d4f): more undefined references to `llvm::raw_string_ostream::current_pos() const' follow
collect2: error: ld returned 1 exit status
```

**Comment by justxi** [comment]
The ebuild works on my system with GCC 10.2.0.
I created another ebuild base on the ebuild in portage (-> -r2) ... I currently try to compile...

**Comment by justxi** [comment]
I deleted the "-r1" version, because there is already a different version in portage.
The second version works also on my system.

**Comment by pshirshov** [comment]
```
>>> Verifying ebuild manifests

!!! A file listed in the Manifest could not be found: /var/lib/layman/rocm/sys-devel/llvm-roc/llvm-roc-3.7.0-r1.ebuild
```

**Comment by pshirshov** [comment]
`-r2` works for me. I had to make a local copy though bcs of the manifest issue.

**Comment by justxi** [comment]
Thanks for the feedback.
I updated the manifest.

**Comment by pshirshov** [comment]
Works now, thanks. I would suggest you to add a simple CI job (on github actions, for example) automatically regenerating manifests for all the ebuilds in your repo.

**Comment by justxi** [comment]
> Works now, thanks. I would suggest you to add a simple CI job (on github actions, for example) automatically regenerating manifests for all the ebuilds in your repo.

Good idea, but I have to figure out how it works.
Or I don´t forgett to update the manifest before I commit ;).

**Comment by pshirshov** [comment]
Well, that's pretty easy, check this overlay: https://github.com/no-hope/fw-overlay/blob/master/.travis.yml
